prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: squad-ecommerce-prod
      environment: prod
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi


grafana:
  enabled: true
  adminPassword: change-me-securely
  
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6

  persistence:
    enabled: true
    storageClassName: standard-rwo
    size: 10Gi
    
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

nodeExporter:
  enabled: true
  operatingSystem: linux

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true
