apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retail-store-catalog
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: retail-store
spec:
  namespaceSelector:
    matchNames:
      - retail-store-stage
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/component: service
      app.kubernetes.io/owner: retail-store-sample
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
