apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: retail-store-disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  app.kubernetes.io/owner: retail-store-sample
                  app.kubernetes.io/component: service
      validate:
        message: "Retail Store service pods must not use the 'latest' image tag."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ contains(element.image, ':latest') }}"
                    operator: Equals
                    value: true
