apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: retail-store-ingress
  namespace: squad-ecomerce-prod
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "squad-prod-static-ip"
spec:
  rules:
  - host: "PLACEHOLDER" 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-prod
            port:
              number: 80