apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andriiklykavkaa/int0-hackaton-devops.git
    targetRevision: main
    path: src/orders/chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: europe-central2-docker.pkg.dev/int-hackaton-uyak/retail-images-prod/retail-store-sample-orders
        - name: image.tag
          value: 44d010f
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "1"
        - name: autoscaling.maxReplicas
          value: "5"
        - name: metrics.enabled
          value: "true"
        - name: app.persistence.provider
          value: postgres
        - name: postgresql.create
          value: "true"
        - name: postgresql.persistentVolume.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
