apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andriiklykavkaa/int0-hackaton-devops.git
    targetRevision: main
    path: src/ui/chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: europe-central2-docker.pkg.dev/int-hackaton-uyak/retail-images-prod/retail-store-sample-ui
        - name: image.tag
          value: 44d010f
        - name: replicaCount
          value: "2"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "2"
        - name: autoscaling.maxReplicas
          value: "10"
        - name: autoscaling.targetCPUUtilizationPercentage
          value: "50"
        - name: podDisruptionBudget.enabled
          value: "true"
        - name: metrics.enabled
          value: "true"
        - name: ingress.enabled
          value: "true"
        - name: app.endpoints.catalog
          value: "http://catalog-prod:80"
        - name: app.endpoints.carts
          value: "http://cart-prod-carts:80"
        - name: app.endpoints.orders
          value: "http://orders-prod:80"
        - name: app.endpoints.checkout
          value: "http://checkout-prod:80"
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
