# Stage environment — Argo CD Application for ui
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andriiklykavkaa/int0-hackaton-devops.git
    targetRevision: main
    path: src/ui/chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: europe-central2-docker.pkg.dev/PROJECT_ID/retail-store/retail-store-sample-ui
        - name: image.tag
          value: latest   # CI updates this to git SHA on merge
        - name: replicaCount
          value: "1"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "1"
        - name: autoscaling.maxReplicas
          value: "5"
        - name: autoscaling.targetCPUUtilizationPercentage
          value: "50"
        - name: metrics.enabled
          value: "true"
        - name: ingress.enabled
          value: "true"
        - name: app.endpoints.catalog
          value: http://catalog.retail-store-stage.svc.cluster.local
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
