name: "Terraform CD (Stage)"

on:
  workflow_run:
      workflows: ["Terraform CI"]
      types:
        - completed
      branches:
        - main

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
  
jobs:
  apply-stage:
    name: 'Terraform Apply (Stage)'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/stage

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve