name: "Terraform CD (Prod)"

on:
  workflow_run:
    workflows: ["Terraform CI (Prod)"]
    types:
      - completed

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
  
jobs:
  apply-prod:
    name: 'TF CD (Prod)'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: ./terraform/environments/prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: squad-ecommerce-prod
          location: europe-central2
          project_id: ${{ env.TF_VAR_project_id }}

      - name: Deploy App of Apps
        run: |
          kubectl apply -f ../../../gitops/argocd/app-of-apps-prod.yaml -n argocd