name: Infrastructure Monitoring

on:
  workflow_dispatch:
  push:
    paths:
      - "platform/monitoring/**"

jobs:
  deploy-prometheus-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: squad-ecommerce-stage # OR prod
          location: europe-central2

      - name: Deploy Monitoring Stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          # Устанавливаем стек: Prometheus, Grafana, Alertmanager и Node Exporter
          helm upgrade --install kube-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            --set grafana.enabled=true \
            --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false